/**
 * Dashboard catalog for Phase 2. In later phases this is sourced from
 * the database (per-tenant published workbooks generated by the Factory).
 *
 * Each entry maps a stable `id` (used in URLs) to the Tableau view path
 * (workbook/sheet). The view path is appended to the site URL by
 * `tableauViewUrl()` to produce the `<TableauViz src=...>` value.
 */
export type DashboardScope = "all" | "internal";

export interface DashboardEntry {
  id: string;
  name: string;
  description: string;
  industry: "retail" | "banking" | "manufacturing" | "healthcare" | "logistics" | "generic";
  viewPath: string;
  scope: DashboardScope;
}

export const DASHBOARD_CATALOG: readonly DashboardEntry[] = [
  {
    id: "retail-executive",
    name: "Retail — Executive Overview",
    description: "Revenue, orders, AOV, gross margin, and top categories at a glance.",
    industry: "retail",
    viewPath: "RetailExecutive/Overview",
    scope: "all",
  },
  {
    id: "retail-regional",
    name: "Retail — Regional Performance",
    description: "Revenue and growth heatmap by region with channel breakdown.",
    industry: "retail",
    viewPath: "RetailExecutive/Regional",
    scope: "all",
  },
  {
    id: "internal-admin-impressions",
    name: "Internal — Impression Usage",
    description: "Per-tenant impression consumption and budget headroom.",
    industry: "generic",
    viewPath: "PortalAdmin/Impressions",
    scope: "internal",
  },
] as const;

export function listDashboardsForTenant(opts: {
  isInternal: boolean;
}): readonly DashboardEntry[] {
  return DASHBOARD_CATALOG.filter((d) => d.scope === "all" || (d.scope === "internal" && opts.isInternal));
}

export function getDashboard(id: string): DashboardEntry | undefined {
  return DASHBOARD_CATALOG.find((d) => d.id === id);
}
