/**
 * Tenant theme registry.
 * - Production (Vercel KV configured): persists to Redis
 * - Local dev: persists to data/tenant-themes.json
 *
 * Server-side only.
 */
import { join } from "path";

export type Tone = "professional" | "playful" | "technical";

export interface TenantTheme {
  tenantId: string;
  companyName: string;
  primaryColor: string;
  secondaryColor: string;
  neutralColor: string;
  sidebarTextColor: string;
  fontFamily: string;
  logoUrl?: string | undefined;
  tone: Tone;
}

const HEX = /^#[0-9a-fA-F]{6}$/;

export const DEFAULT_THEME: Omit<TenantTheme, "tenantId"> = {
  companyName: "Salesforce Bank",
  primaryColor: "#0176d3",
  secondaryColor: "#f5a623",
  neutralColor: "#032d60",
  sidebarTextColor: "#ffffff",
  fontFamily: "Inter",
  tone: "professional",
};

// ── Storage helpers ──────────────────────────────────────────────────────────

function hasKv(): boolean {
  return !!(process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN);
}

function kvKey(tenantId: string): string {
  return `tenant-theme:${tenantId}`;
}

async function readFromKv(tenantId: string): Promise<TenantTheme | null> {
  const { kv } = await import("@vercel/kv");
  return kv.get<TenantTheme>(kvKey(tenantId));
}

async function writeToKv(theme: TenantTheme): Promise<void> {
  const { kv } = await import("@vercel/kv");
  await kv.set(kvKey(theme.tenantId), theme);
}

async function deleteFromKv(tenantId: string): Promise<void> {
  const { kv } = await import("@vercel/kv");
  await kv.del(kvKey(tenantId));
}

async function readAllFromFile(): Promise<Map<string, TenantTheme>> {
  const { readFile } = await import("fs/promises");
  try {
    const raw = await readFile(join(process.cwd(), "data", "tenant-themes.json"), "utf-8");
    const arr = JSON.parse(raw) as TenantTheme[];
    return new Map(arr.map((t) => [t.tenantId, t]));
  } catch {
    return new Map();
  }
}

async function writeAllToFile(store: Map<string, TenantTheme>): Promise<void> {
  const { writeFile, mkdir } = await import("fs/promises");
  const dir = join(process.cwd(), "data");
  await mkdir(dir, { recursive: true });
  await writeFile(
    join(dir, "tenant-themes.json"),
    JSON.stringify([...store.values()], null, 2) + "\n",
    "utf-8",
  );
}

// ── Public API ───────────────────────────────────────────────────────────────

export async function getTenantTheme(tenantId: string): Promise<TenantTheme> {
  if (hasKv()) {
    return (await readFromKv(tenantId)) ?? { tenantId, ...DEFAULT_THEME };
  }
  const store = await readAllFromFile();
  return store.get(tenantId) ?? { tenantId, ...DEFAULT_THEME };
}

export async function setTenantTheme(
  input: Partial<TenantTheme> & { tenantId: string },
): Promise<TenantTheme> {
  const existing = await getTenantTheme(input.tenantId);
  const next: TenantTheme = {
    tenantId: input.tenantId,
    companyName: (input.companyName ?? existing.companyName).slice(0, 120),
    primaryColor: pickHex(input.primaryColor, existing.primaryColor),
    secondaryColor: pickHex(input.secondaryColor, existing.secondaryColor),
    neutralColor: pickHex(input.neutralColor, existing.neutralColor),
    sidebarTextColor: pickHex(input.sidebarTextColor, existing.sidebarTextColor),
    fontFamily: (input.fontFamily ?? existing.fontFamily).slice(0, 80),
    tone: isTone(input.tone) ? input.tone : existing.tone,
    ...(input.logoUrl !== undefined
      ? { logoUrl: String(input.logoUrl).slice(0, 2048) }
      : existing.logoUrl !== undefined
        ? { logoUrl: existing.logoUrl }
        : {}),
  };

  if (hasKv()) {
    await writeToKv(next);
  } else {
    const store = await readAllFromFile();
    store.set(next.tenantId, next);
    await writeAllToFile(store);
  }
  return next;
}

export async function deleteTenantTheme(tenantId: string): Promise<boolean> {
  if (hasKv()) {
    await deleteFromKv(tenantId);
    return true;
  }
  const store = await readAllFromFile();
  const deleted = store.delete(tenantId);
  if (deleted) await writeAllToFile(store);
  return deleted;
}

// ── Per-tenant DESIGN.md (generated by factory Stage 11) ────────────────────

function designKey(tenantId: string): string {
  return `tenant-design:${tenantId}`;
}

export async function getTenantDesignMd(tenantId: string): Promise<string | null> {
  if (hasKv()) {
    const { kv } = await import("@vercel/kv");
    return kv.get<string>(designKey(tenantId));
  }
  const { readFile } = await import("fs/promises");
  const { join } = await import("path");
  try {
    return await readFile(join(process.cwd(), "data", "tenant-designs", `${tenantId}.md`), "utf-8");
  } catch {
    return null;
  }
}

// ── CSS variable helpers ─────────────────────────────────────────────────────

export function themeToCssVariables(theme: TenantTheme): string {
  const textColor = theme.sidebarTextColor ?? "#ffffff";
  return [
    `--brand-primary: ${theme.primaryColor};`,
    `--brand-secondary: ${theme.secondaryColor};`,
    `--brand-neutral: ${theme.neutralColor};`,
    `--sidebar-text: ${textColor};`,
    `--sidebar-text-muted: ${textColor}99;`,
    `--sidebar-text-dim: ${textColor}66;`,
    `--font-sans: ${theme.fontFamily}, Inter, system-ui, sans-serif;`,
  ].join(" ");
}

function pickHex(candidate: string | undefined, fallback: string): string {
  if (candidate && HEX.test(candidate)) return candidate.toLowerCase();
  return fallback;
}

function isTone(v: unknown): v is Tone {
  return v === "professional" || v === "playful" || v === "technical";
}
