import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/lib/auth";
import { tenantFromSession } from "@/lib/tenant";
import { listTenants } from "@/lib/tenants";
import { getImpressionStatus } from "@/lib/billing";

export default async function TenantsAdminPage() {
  const session = await auth();
  const ctx = tenantFromSession(session);
  if (!ctx?.isInternal) notFound();

  const tenants = await listTenants();
  const usage = await Promise.all(
    tenants.map(async (t) => ({ ...t, status_: t.status, impressions: await getImpressionStatus(t.id) })),
  );

  return (
    <main className="mx-auto max-w-5xl space-y-4 px-6 py-8">
      <nav className="flex gap-3 text-sm">
        <span className="font-semibold">Tenants</span>
        <span className="text-[hsl(var(--muted-foreground))]">·</span>
        <Link href="/admin/portals" className="text-[hsl(var(--muted-foreground))] hover:underline">
          Portal Catalog
        </Link>
        <span className="text-[hsl(var(--muted-foreground))]">·</span>
        <Link href="/admin/sites" className="text-[hsl(var(--muted-foreground))] hover:underline">
          Tableau Sites
        </Link>
        <span className="text-[hsl(var(--muted-foreground))]">·</span>
        <Link href="/admin/impressions" className="text-[hsl(var(--muted-foreground))] hover:underline">
          Impressions
        </Link>
      </nav>
      <header className="flex items-end justify-between">
        <div>
          <p className="text-xs uppercase tracking-wide text-[hsl(var(--muted-foreground))]">
            Internal admin
          </p>
          <h1 className="text-2xl font-semibold">Tenants</h1>
          <p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">
            Active demo tenants generated by the factory or seeded manually.
          </p>
        </div>
        <Link
          href="/factory/new"
          className="rounded-md bg-brand px-3 py-1.5 text-sm font-medium text-white hover:opacity-90"
        >
          + New tenant
        </Link>
      </header>

      <table className="w-full overflow-hidden rounded-lg border border-[hsl(var(--border))] text-sm">
        <thead className="bg-[hsl(var(--muted))]">
          <tr>
            <th className="px-4 py-2 text-left font-medium">Tenant</th>
            <th className="px-4 py-2 text-left font-medium">Slug</th>
            <th className="px-4 py-2 text-left font-medium">Industry</th>
            <th className="px-4 py-2 text-right font-medium">Impressions</th>
            <th className="px-4 py-2 text-left font-medium">Status</th>
            <th className="px-4 py-2 text-left font-medium" />
          </tr>
        </thead>
        <tbody>
          {usage.map((t) => (
            <tr key={t.id} className="border-t border-[hsl(var(--border))]">
              <td className="px-4 py-2 font-medium">{t.name}</td>
              <td className="px-4 py-2 font-mono text-xs">{t.slug}</td>
              <td className="px-4 py-2 text-xs">{t.industry}</td>
              <td className="px-4 py-2 text-right font-mono">
                {t.impressions.used} / {t.impressions.cap}
              </td>
              <td className="px-4 py-2">
                {t.status_ === "active" ? (
                  <span className="rounded bg-green-100 px-2 py-0.5 text-xs text-green-800">active</span>
                ) : (
                  <span className="rounded bg-[hsl(var(--muted))] px-2 py-0.5 text-xs">archived</span>
                )}
              </td>
              <td className="px-4 py-2">
                <Link href={`/admin/tenants/${t.slug}`} className="text-xs underline">
                  Manage
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}
