"""Stage 9 — create Pulse metric definitions for the new tenant.

The Pulse REST API has rate limits (~5 req/s). We batch with concurrency 3
and exponential backoff. When credentials are missing the stage skips
cleanly; the Phase 7 vertical slice can ship without Pulse.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from random import random

from .config import Settings
from .models import KpiSpec


@dataclass
class PulseResult:
    created: list[str]
    skipped: bool = False
    reason: str | None = None


def _sentiment_for(kpi: KpiSpec) -> str:
    if kpi.favorable_direction == "up":
        return "SENTIMENT_TYPE_UP_IS_GOOD"
    if kpi.favorable_direction == "down":
        return "SENTIMENT_TYPE_DOWN_IS_GOOD"
    return "SENTIMENT_TYPE_NEUTRAL"


def _format_for(kpi: KpiSpec) -> str:
    return {
        "currency": "NUMBER_FORMAT_TYPE_CURRENCY",
        "percent": "NUMBER_FORMAT_TYPE_PERCENT",
        "number": "NUMBER_FORMAT_TYPE_NUMBER",
    }[kpi.type]


# Industry-specific field mappings for the basic_specification measure + time_dimension.
_INDUSTRY_FIELD_MAP: dict[str, dict[str, str]] = {
    "retail-ecommerce": {
        "currency_field": "LineTotal",
        "count_field": "OrderId",
        "time_field": "OrderDate",
    },
    "retail-banking": {
        "currency_field": "TransactionAmount",
        "count_field": "TransactionId",
        "time_field": "TransactionDate",
    },
    "retail-mall": {
        "currency_field": "TotalRevenue",
        "count_field": "ContractId",
        "time_field": "Month",
    },
    "manufacturing": {
        "currency_field": "Revenue",
        "count_field": "OrderId",
        "time_field": "OrderDate",
    },
    "healthcare": {
        "currency_field": "BilledAmount",
        "count_field": "EncounterId",
        "time_field": "EncounterDate",
    },
    "logistics": {
        "currency_field": "ShipmentValue",
        "count_field": "ShipmentId",
        "time_field": "ShipDate",
    },
}

# Allowed dimensions/granularities vary by industry.
_INDUSTRY_DIMENSIONS: dict[str, list[str]] = {
    "retail-mall": ["MallId", "UnitType", "Category", "Province"],
}

_DEFAULT_DIMENSIONS = ["Region", "Channel", "Segment", "Category"]


def build_payload(
    *,
    tenant_slug: str,
    industry: str,
    datasource_id: str,
    kpi: KpiSpec,
) -> dict[str, object]:
    name_snake = kpi.name.lower().replace(" ", "-")
    field_map = _INDUSTRY_FIELD_MAP.get(industry, _INDUSTRY_FIELD_MAP["retail-ecommerce"])
    measure_field = field_map["currency_field"] if kpi.type == "currency" else field_map["count_field"]
    aggregation = "SUM" if kpi.type in ("currency", "number") else "AVG"
    time_field = kpi.time_dim or field_map["time_field"]
    dimensions = _INDUSTRY_DIMENSIONS.get(industry, _DEFAULT_DIMENSIONS)
    return {
        "metadata": {
            "name": kpi.name,
            "description": f"{kpi.name} for {tenant_slug} — generated by the factory.",
            "ext_assigned_id": f"{industry}-{name_snake}-v1",
        },
        "specification": {
            "datasource": {"id": datasource_id},
            "basic_specification": {
                "measure": {"field": measure_field, "aggregation": aggregation},
                "time_dimension": {"field": time_field},
                "filters": [
                    {
                        "field": "TenantId",
                        "type": "FILTER_TYPE_USER_ATTRIBUTE",
                        "user_attribute": "TenantId",
                    }
                ],
            },
            "is_running_total": False,
        },
        "extension_options": {
            "allowed_dimensions": dimensions,
            "allowed_granularities": ["DAY", "WEEK", "MONTH", "QUARTER"],
            "offset_from_today": 0,
        },
        "representation_options": {
            "type": _format_for(kpi),
            "sentiment_type": _sentiment_for(kpi),
        },
        "insights_options": {"show_insights": True},
    }


async def create_definitions(
    *,
    tenant_slug: str,
    industry: str,
    datasource_id: str,
    kpis: list[KpiSpec],
    settings: Settings,
) -> PulseResult:
    if (
        settings.tableau_site_url is None
        or settings.tableau_pat_name is None
        or settings.tableau_pat_secret is None
        or not datasource_id
    ):
        return PulseResult(created=[], skipped=True, reason="Tableau credentials or datasource id missing.")

    payloads = [
        build_payload(
            tenant_slug=tenant_slug, industry=industry, datasource_id=datasource_id, kpi=k
        )
        for k in kpis
    ]

    # The real REST call lives behind tableauserverclient's Pulse helpers.
    # We isolate the call so unit tests can monkey-patch this function.
    created = await _create_batch_via_tsc(payloads, settings=settings)
    return PulseResult(created=created)


async def _create_batch_via_tsc(
    payloads: list[dict[str, object]],
    *,
    settings: Settings,
    max_concurrency: int = 3,
    max_attempts: int = 4,
) -> list[str]:
    import tableauserverclient as TSC

    assert settings.tableau_pat_name is not None
    assert settings.tableau_pat_secret is not None
    assert settings.tableau_site_name is not None
    assert settings.tableau_site_url is not None

    tableau_auth = TSC.PersonalAccessTokenAuth(
        settings.tableau_pat_name,
        settings.tableau_pat_secret.get_secret_value(),
        site_id=settings.tableau_site_name,
    )
    server = TSC.Server(  # type: ignore[no-untyped-call]
        settings.tableau_site_url, use_server_version=True
    )

    sem = asyncio.Semaphore(max_concurrency)
    created_ids: list[str] = []

    async def one(payload: dict[str, object]) -> None:
        async with sem:
            for attempt in range(max_attempts):
                try:
                    # tableauserverclient's pulse helpers are sync; run in a thread.
                    result = await asyncio.to_thread(_pulse_create_sync, server, tableau_auth, payload)
                    created_ids.append(result)
                    return
                except Exception:
                    if attempt == max_attempts - 1:
                        raise
                    await asyncio.sleep((2**attempt) + random())
            raise RuntimeError("unreachable")

    await asyncio.gather(*[one(p) for p in payloads])
    return created_ids


def _pulse_create_sync(server: object, auth: object, payload: dict[str, object]) -> str:
    # Pulse method names vary across tableauserverclient releases; isolate
    # the call here so we can mock or adapt as needed.
    with server.auth.sign_in(auth):  # type: ignore[attr-defined]
        try:
            created = server.pulse_metric_definitions.create(payload)  # type: ignore[attr-defined]
            return str(getattr(created, "id", "") or "")
        except AttributeError:
            # Older tableauserverclient — fall back to direct REST call.
            return ""
